CREATE PROFILE C##GAMES_BASE_PROFILE LIMIT
    PASSWORD_LIFE_TIME 180
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;

CREATE ROLE C##SYSADMIN_ROLE;
GRANT CREATE SESSION TO C##SYSADMIN_ROLE;
GRANT EXECUTE ANY PROCEDURE TO C##SYSADMIN_ROLE;
GRANT CREATE SEQUENCE TO C##SYSADMIN_ROLE;
GRANT EXECUTE ON GamesAdminPackage TO C##SYSADMIN_ROLE;

CREATE ROLE C##CLIENT_ROLE;
GRANT CREATE SESSION TO C##CLIENT_ROLE;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO C##CLIENT_ROLE; -- sysdba
GRANT EXECUTE ON GamesClientPackage TO C##CLIENT_ROLE;

CREATE USER C##SYSADMIN IDENTIFIED BY PUK
    PROFILE C##GAMES_BASE_PROFILE
    ACCOUNT UNLOCK;
GRANT C##SYSADMIN_ROLE TO C##SYSADMIN;

CREATE USER C##SHOP_CLIENT IDENTIFIED BY PUK
  PROFILE C##GAMES_BASE_PROFILE
  ACCOUNT UNLOCK;
GRANT C##CLIENT_ROLE TO C##SHOP_CLIENT;
