-- All games
CREATE SEQUENCE GamesIdSequence;
CREATE TABLE Games
(
    ID INT DEFAULT GamesIdSequence.nextval PRIMARY KEY,
    SUPPLIER INT NOT NULL,
    AUTHOR INT NOT NULL,
    GAME_TYPE INT NOT NULL,
    NAME NVARCHAR2 (50) NOT NULL,
    COST NUMBER CHECK ( COST > 0 ) NOT NULL
);

-- Game types
CREATE SEQUENCE GameTypesIdSequence;
CREATE TABLE GameTypes
(
    ID INT DEFAULT GameTypesIdSequence.nextval PRIMARY KEY,
    NAME NVARCHAR2 (50) UNIQUE,
    PLAYERS_COUNT INT CHECK ( PLAYERS_COUNT > 0 )
);

-- Game authors
CREATE SEQUENCE AuthorsSequence;
CREATE TABLE Authors
(
    ID INT DEFAULT AuthorsSequence.nextval PRIMARY KEY,
    NAME NVARCHAR2(50) NOT NULL,
    PHONE_NUMBER NVARCHAR2(20) NOT NULL,
    ADDRESS NVARCHAR2(50) NOT NULL
);

-- Game supplierse
CREATE SEQUENCE SuppliersIdSequence;
CREATE TABLE Suppliers
(
    ID INT DEFAULT SuppliersIdSequence.nextval PRIMARY KEY,
    NAME NVARCHAR2 (50) UNIQUE,
    ADDRESS NVARCHAR2 (70) NOT NULL,
    PHONE_NUMBER NVARCHAR2 (20) NOT NULL
);

-- Client's orders
CREATE SEQUENCE OrdersIdSequence;
CREATE TABLE Orders
(
    ID INT DEFAULT OrdersIdSequence.nextval PRIMARY KEY,
    GAME INT NOT NULL,
    CLIENT INT NOT NULL,
    STAFF INT NOT NULL,
    ORDER_DATE DATE DEFAULT SYSDATE NOT NULL
);

-- Shop clients
CREATE SEQUENCE ClientsSequence;
CREATE TABLE Clients
(
    ID INT DEFAULT ClientsSequence.nextval PRIMARY KEY,
    NAME NVARCHAR2(50) NOT NULL,
    ADDRESS NVARCHAR2(70) NOT NULL,
    PHONE_NUMBER NVARCHAR2(50) NOT NULL,
    LOGIN NVARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD NVARCHAR2(50) CHECK ( LENGTH(PASSWORD) > 8 )
);

-- Staff data
CREATE SEQUENCE StaffSequence;
CREATE TABLE Staff
(
    ID INT DEFAULT StaffSequence.nextval PRIMARY KEY,
    POSITION INT NOT NULL,
    PHONE_NUMBER NVARCHAR2 (50) NOT NULL,
    NAME NVARCHAR2(50) NOT NULL
);

-- Positions
CREATE SEQUENCE PositionSequence;
CREATE TABLE Positions
(
    ID INT DEFAULT PositionSequence.nextval PRIMARY KEY,
    NAME NVARCHAR2(50) NOT NULL,
    SALARY INT NOT NULL CHECK ( SALARY > 0 )
);

ALTER TABLE Games ADD CONSTRAINT GamesFkSupplier FOREIGN KEY (SUPPLIER) REFERENCES Suppliers(ID); -- Games + supplires
ALTER TABLE Games ADD CONSTRAINT GamesFkAuthor FOREIGN KEY (AUTHOR) REFERENCES Authors(ID); -- Games + authors
ALTER TABLE Games ADD CONSTRAINT GamesFkType FOREIGN KEY (GAME_TYPE) REFERENCES GameTypes(ID); -- Games + types

ALTER TABLE Orders ADD CONSTRAINT OrdersFkGame FOREIGN KEY (GAME) REFERENCES Games(ID); -- Orders + games
ALTER TABLE Orders ADD CONSTRAINT OrdersFkClient FOREIGN KEY (CLIENT) REFERENCES Clients(ID); -- Orders + clients
ALTER TABLE Orders ADD CONSTRAINT OrdersFkStaff FOREIGN KEY (STAFF) REFERENCES Staff(ID); -- Orders + staff

ALTER TABLE Staff ADD CONSTRAINT StaffFkPosition FOREIGN KEY (POSITION) REFERENCES Positions(ID); -- Staff + positions

ALTER TABLE Staff DROP CONSTRAINT StaffFkPosition;
ALTER TABLE Games DROP CONSTRAINT GamesFkSupplier;
ALTER TABLE Games DROP CONSTRAINT GamesFkAuthor;
ALTER TABLE Games DROP CONSTRAINT GamesFkType;
ALTER TABLE Orders DROP CONSTRAINT OrdersFkGame;
ALTER TABLE Orders DROP CONSTRAINT OrdersFkClient;
ALTER TABLE Orders DROP CONSTRAINT OrdersFkStaff;

commit;

DROP TABLE Staff;
DROP TABLE Positions;
DROP TABLE Clients;
DROP TABLE Orders;
DROP TABLE Suppliers;
DROP TABLE Authors;
DROP TABLE GameTypes;
DROP TABLE Games;

DROP SEQUENCE GamesIdSequence;
DROP SEQUENCE GameTypesIdSequence;
DROP SEQUENCE AuthorsSequence;
DROP SEQUENCE SuppliersIdSequence;
DROP SEQUENCE OrdersIdSequence;
DROP SEQUENCE ClientsSequence;
DROP SEQUENCE StaffSequence;
DROP SEQUENCE PositionSequence;