CREATE SEQUENCE GamesIdSequence;
CREATE TABLE Games
(
    ID INT DEFAULT GamesIdSequence.nextval PRIMARY KEY,
    SUPPLIER INT NOT NULL,
    AUTHOR INT NOT NULL,
    GAME_TYPE INT NOT NULL,
    NAME NVARCHAR2 (50) NOT NULL,
    COST NUMBER CHECK ( COST > 0 ) NOT NULL
);

CREATE SEQUENCE GameTypesIdSequence;
CREATE TABLE GameTypes
(
    ID INT DEFAULT GameTypesIdSequence.nextval PRIMARY KEY,
    NAME NVARCHAR2 (50) UNIQUE,
    PLAYERS_COUNT INT CHECK ( PLAYERS_COUNT > 0 )
);

CREATE SEQUENCE AuthorsSequence;
CREATE TABLE Authors
(
    ID INT DEFAULT AuthorsSequence.nextval PRIMARY KEY,
    NAME NVARCHAR2(50) NOT NULL,
    PHONE_NUMBER NVARCHAR2(20) NOT NULL,
    ADDRESS NVARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SuppliersIdSequence;
CREATE TABLE Suppliers
(
    ID INT DEFAULT SuppliersIdSequence.nextval PRIMARY KEY,
    NAME NVARCHAR2 (50) UNIQUE,
    ADDRESS NVARCHAR2 (70) NOT NULL,
    PHONE_NUMBER NVARCHAR2 (20) NOT NULL
);

CREATE SEQUENCE OrdersIdSequence;
CREATE TABLE Orders
(
    ID INT DEFAULT OrdersIdSequence.nextval PRIMARY KEY,
    GAME INT NOT NULL,
    CLIENT INT NOT NULL,
    STAFF INT NOT NULL,
    ORDER_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE ClientsSequence;
CREATE TABLE Clients
(
    ID INT DEFAULT ClientsSequence.nextval PRIMARY KEY,
    NAME NVARCHAR2(50) NOT NULL,
    ADDRESS NVARCHAR2(70) NOT NULL,
    PHONE_NUMBER NVARCHAR2(50) NOT NULL,
    LOGIN NVARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD NVARCHAR2(50) CHECK ( LENGTH(PASSWORD) > 8 )
);

CREATE SEQUENCE StaffSequence;
CREATE TABLE Staff
(
    ID INT DEFAULT StaffSequence.nextval PRIMARY KEY,
    POSITION INT NOT NULL,
    PHONE_NUMBER NVARCHAR2 (50) NOT NULL,
    NAME NVARCHAR2(50) NOT NULL
);

CREATE SEQUENCE PositionSequence;
CREATE TABLE Positions
(
    ID INT DEFAULT PositionSequence.nextval PRIMARY KEY,
    NAME NVARCHAR2(50) NOT NULL,
    SALARY INT NOT NULL CHECK ( SALARY > 0 )
);

ALTER TABLE Games ADD CONSTRAINT GamesFkSupplier FOREIGN KEY (SUPPLIER) REFERENCES Suppliers(ID);
ALTER TABLE Games ADD CONSTRAINT GamesFkAuthor FOREIGN KEY (AUTHOR) REFERENCES Authors(ID);
ALTER TABLE Games ADD CONSTRAINT GamesFkType FOREIGN KEY (GAME_TYPE) REFERENCES GameTypes(ID);

ALTER TABLE Orders ADD CONSTRAINT OrdersFkGame FOREIGN KEY (GAME) REFERENCES Games(ID);
ALTER TABLE Orders ADD CONSTRAINT OrdersFkClient FOREIGN KEY (CLIENT) REFERENCES Clients(ID);
ALTER TABLE Orders ADD CONSTRAINT OrdersFkStaff FOREIGN KEY (STAFF) REFERENCES Staff(ID);

ALTER TABLE Staff ADD CONSTRAINT StaffFkPosition FOREIGN KEY (POSITION) REFERENCES Positions(ID);

ALTER TABLE Staff DROP CONSTRAINT StaffFkPosition;
ALTER TABLE Games DROP CONSTRAINT GamesFkSupplier;
ALTER TABLE Games DROP CONSTRAINT GamesFkAuthor;
ALTER TABLE Games DROP CONSTRAINT GamesFkType;
ALTER TABLE Orders DROP CONSTRAINT OrdersFkGame;
ALTER TABLE Orders DROP CONSTRAINT OrdersFkClient;
ALTER TABLE Orders DROP CONSTRAINT OrdersFkStaff;

DROP TABLE Staff;
DROP TABLE Positions;;
DROP TABLE Clients;
DROP TABLE Orders;
DROP TABLE Suppliers;
DROP TABLE Authors;
DROP TABLE GameTypes;
DROP TABLE Games;
