CREATE OR REPLACE PACKAGE GamesClientPackage
IS
    PROCEDURE AddOrder(pGame Orders.GAME%TYPE, pClient Orders.CLIENT%TYPE, pStaff Orders.STAFF%TYPE, pDate Orders.ORDER_DATE%TYPE);
    PROCEDURE GetGame(ID GAMES.ID%TYPE);
END;

CREATE OR REPLACE PACKAGE BODY GamesClientPackage
IS
    PROCEDURE AddOrder(pGame Orders.GAME%TYPE, pClient Orders.CLIENT%TYPE, pStaff Orders.STAFF%TYPE, pDate Orders.ORDER_DATE%TYPE) IS
    BEGIN
        GamesAdminPackage.AddOrder(pGame, pClient, pStaff, pDate);
        EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.put_line(sqlerrm);
    END;
    PROCEDURE GetGame(ID GAMES.ID%TYPE) AS
        CURSOR CUR IS SELECT * FROM GAME_INFO WHERE GAME_INFO.ID = ID;
        REC GAME_INFO%ROWTYPE;
    BEGIN
        OPEN CUR;
        FETCH CUR INTO REC;
        CLOSE CUR;

        DBMS_OUTPUT.PUT_LINE('GAME_NAME: ' || REC.GAME_NAME);
        DBMS_OUTPUT.PUT_LINE('TYPE_NAME: ' || REC.TYPE_NAME);
        DBMS_OUTPUT.PUT_LINE('AUTHOR: ' || REC.AUTHOR);
        DBMS_OUTPUT.PUT_LINE('PLAYERS_COUNT: ' || REC.PLAYERS_COUNT);
        DBMS_OUTPUT.PUT_LINE('SUPPLIER: ' || REC.SUPPLIER);
    END;
END;

commit;

BEGIN
    GamesClientPackage.GetGame(1);
end;

create OR REPLACE view GAME_INFO as
SELECT GAMES.ID ID, GAMES.NAME GAME_NAME, G.NAME TYPE_NAME, G.PLAYERS_COUNT PLAYERS_COUNT, A2.NAME AUTHOR, S.NAME SUPPLIER FROM GAMES
    JOIN GAMETYPES G on GAMES.GAME_TYPE = G.ID
    JOIN AUTHORS A2 on GAMES.AUTHOR = A2.ID
    JOIN SUPPLIERS S on GAMES.SUPPLIER = S.ID;